### PR TITLE
refactor: add header

### PR DESCRIPTION
**Pull request by cirias**

### CODE REVIEW

**Comment by jingqiuELE** [comment]
Hi cirias,
  I will read the code in more detail at a later time. Just went over it roughly, and I think it is too complicated to put the reconnect logic into protocol layer. Now the protocol must know all things: the state machine of when to do a reconnect, the packet type, etc. 
  To solve the reconnect problem, my suggestion is to add another module which sits above of protocol. This layer would keep the status of the connection and reconnect if needed. The packet type is known in this layer, not in "protocol". The protocol would only needs to handle tcp and udp connections as it does originally...

Regards,
Jing

**Comment by cirias** [comment]
You are right. I can't decouple reconnection from protocol because I choose to use connection as user identity. It has been proved to be a fault. :sob:

But I won't update it in the near future. I am coming to embarce petrel :satisfied:

**Comment by jingqiuELE** [comment]
Hi Cirias,
  I'm currently occupied in other stuff and haven't really look into the details of code. Originally what bothered me most is the way Dail(...) implemented. As I have been used to the socket idiom of Dial, I found it too difficult to understand as Dail would do reconnect itself. 
   I really liked the original way of myvpn, very simple and elegant. But the simple protocol before seems to be bloated with so many features now, so it becomes heavy and harder to understand.
   Of course, those are just my personal opinions. I understand we all have to make choices;-)
   Anyways, allow me some more time to take a closer look and merge it.

Thank you,
Jing

**Comment by cirias** [comment]
Thank you so much for your advice. Don't worry. It's not emergency. I may add some changes if I have free time.

**Comment by cirias** [comment]
I decide to implement reconnection in a different way.

**Pull request closed without merging**
